# Transportation variables
self.modvar_trns_average_vehicle_load_freight = "Average Freight Vehicle Load"
self.modvar_trns_average_passenger_occupancy = "Average Passenger Vehicle Occupancy Rate"
self.modvar_trns_electrical_efficiency = "Electrical Vehicle Efficiency"
self.modvar_trns_ef_combustion_mobile_biofuels_ch4 = ":math:`\text{CH}_4` Biofuels Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_diesel_ch4 = ":math:`\text{CH}_4` Diesel Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_gasoline_ch4 = ":math:`\text{CH}_4` Gasoline Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_kerosene_ch4 = ":math:`\text{CH}_4` Kerosene Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_natural_gas_ch4 = ":math:`\text{CH}_4` Natural Gas Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_biofuels_n2o = ":math:`\text{N}_2\text{O}` Biofuels Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_diesel_n2o = ":math:`\text{N}_2\text{O}` Diesel Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_gasoline_n2o = ":math:`\text{N}_2\text{O}` Gasoline Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_kerosene_n2o = ":math:`\text{N}_2\text{O}` Kerosene Mobile Combustion Emission Factor"
self.modvar_trns_ef_combustion_mobile_natural_gas_n2o = ":math:`\text{N}_2\text{O}` Natural Gas Mobile Combustion Emission Factor"
self.modvar_trns_fuel_demand_biofuels_agg = "Total Fuel Demand Biofuels"
self.modvar_trns_fuel_demand_diesel_agg = "Total Fuel Demand Diesel"
self.modvar_trns_fuel_demand_gasoline_agg = "Total Fuel Demand Gasoline"
self.modvar_trns_fuel_demand_hydrogen_agg = "Total Fuel Demand Hydrogen"
self.modvar_trns_fuel_demand_kerosene_agg = "Total Fuel Demand Biofuels"
self.modvar_trns_fuel_demand_natural_gas_agg = "Total Fuel Demand NaturalGas"
self.modvar_trns_fuel_efficiency_biofuels = "Fuel Efficiency Biofuels"
self.modvar_trns_fuel_efficiency_diesel = "Fuel Efficiency Diesel"
self.modvar_trns_fuel_efficiency_gasoline = "Fuel Efficiency Gasoline"
self.modvar_trns_fuel_efficiency_hydrogen = "Fuel Efficiency Hydrogen"
self.modvar_trns_fuel_efficiency_kerosene = "Fuel Efficiency Kerosene"
self.modvar_trns_fuel_efficiency_natural_gas = "Fuel Efficiency Natural Gas"
self.modvar_trns_modeshare_freight = "Freight Transportation Mode Share"
self.modvar_trns_modeshare_public_private = "Private and Public Transportation Mode Share"
self.modvar_trns_modeshare_regional = "Regional Transportation Mode Share"
self.modvar_trns_fuel_fraction_biofuels = "Transportation Mode Fuel Fraction Biofuels"
self.modvar_trns_fuel_fraction_diesel = "Transportation Mode Fuel Fraction Diesel"
self.modvar_trns_fuel_fraction_electricity = "Transportation Mode Fuel Fraction Electricity"
self.modvar_trns_fuel_fraction_gasoline = "Transportation Mode Fuel Fraction Gasoline"
self.modvar_trns_fuel_fraction_hydrogen = "Transportation Mode Fuel Fraction Hydrogen"
self.modvar_trns_fuel_fraction_kerosene = "Transportation Mode Fuel Fraction Kerosene"
self.modvar_trns_fuel_fraction_natural_gas = "Transportation Mode Fuel Fraction Natural Gas"
self.modvar_tnrs_energy_demand_electricity = "Electrical Energy Demand from Transportation"
self.modvar_tnrs_energy_demand_electricity_agg = "Total Electrical Energy Demand from Transportation"
self.modvar_trns_emissions_ch4 = ":math:`\text{CH}_4` Emissions from Transportation"
self.modvar_trns_emissions_co2 = ":math:`\text{CO}_2` Emissions from Transportation"
self.modvar_trns_emissions_n2o = ":math:`\text{N}_2\text{O}` Emissions from Transportation"
self.modvar_trns_vehicle_distance_traveled = "Total Vehicle Distance Traveled"

# Transportation Demand variables
self.modvar_trde_demand_scalar = "Transportation Demand Scalar"
self.modvar_trde_elasticity_mtkm_to_gdp = "Elasticity of Megatonne-Kilometer Demand to GDP"
self.modvar_trde_elasticity_pkm_to_gdp = "Elasticity of Passenger-Kilometer Demand per Capita to GDP per Capita"
self.modvar_trde_demand_initial_mtkm = "Initial Megatonne-Kilometer Demand"
self.modvar_trde_demand_initial_pkm_per_capita = "Initial per Capita Passenger-Kilometer Demand"
self.modvar_trde_demand_mtkm = "Megatonne-Kilometer Demand"
self.modvar_trde_demand_pkm = "Passenger-Kilometer Demand"


self.modvar_enfu_volumetric_energy_density = "Volumetric Energy Density"
